### ISSUE TITLE
How to build this repo?

### ISSUE THREAD

**Issue by myocytebd** [shuen4/jasshelper#1]
How to build this repo?  
Is it possible to build this repo with FPC?  
Thanks.

**Comment by shuen4** [comment]
> How to build this repo?

use `Borland Developer Studio 2006` open project grop(jasshelper.bdsgroup), then `Project -> Build all projects`

> Is it possible to build this repo with FPC?

u can try it urself but i think its impossible if u does not change project setting and/or source code
